// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "climatehero/models"
)

// GetUserInfoOKCode is the HTTP code returned for type GetUserInfoOK
const GetUserInfoOKCode int = 200

/*GetUserInfoOK success

swagger:response getUserInfoOK
*/
type GetUserInfoOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserInfo `json:"body,omitempty"`
}

// NewGetUserInfoOK creates GetUserInfoOK with default headers values
func NewGetUserInfoOK() *GetUserInfoOK {

	return &GetUserInfoOK{}
}

// WithPayload adds the payload to the get user info o k response
func (o *GetUserInfoOK) WithPayload(payload *models.UserInfo) *GetUserInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user info o k response
func (o *GetUserInfoOK) SetPayload(payload *models.UserInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetUserInfoDefault unexpected error

swagger:response getUserInfoDefault
*/
type GetUserInfoDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUserInfoDefault creates GetUserInfoDefault with default headers values
func NewGetUserInfoDefault(code int) *GetUserInfoDefault {
	if code <= 0 {
		code = 500
	}

	return &GetUserInfoDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get user info default response
func (o *GetUserInfoDefault) WithStatusCode(code int) *GetUserInfoDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get user info default response
func (o *GetUserInfoDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get user info default response
func (o *GetUserInfoDefault) WithPayload(payload *models.Error) *GetUserInfoDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user info default response
func (o *GetUserInfoDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserInfoDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
