/*
 * Climate Hero
 * A web app to incentivize users to be more eco-friendly
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CheckReturn
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-12T18:02:17.553-07:00[America/Los_Angeles]")
public class CheckReturn {
  public static final String SERIALIZED_NAME_POINTS = "points";
  @SerializedName(SERIALIZED_NAME_POINTS)
  private Long points;

  public static final String SERIALIZED_NAME_POINTS_MESSAGE = "pointsMessage";
  @SerializedName(SERIALIZED_NAME_POINTS_MESSAGE)
  private String pointsMessage;


  public CheckReturn points(Long points) {
    
    this.points = points;
    return this;
  }

   /**
   * Get points
   * @return points
  **/
  @ApiModelProperty(required = true, value = "")

  public Long getPoints() {
    return points;
  }



  public void setPoints(Long points) {
    this.points = points;
  }


  public CheckReturn pointsMessage(String pointsMessage) {
    
    this.pointsMessage = pointsMessage;
    return this;
  }

   /**
   * Get pointsMessage
   * @return pointsMessage
  **/
  @ApiModelProperty(required = true, value = "")

  public String getPointsMessage() {
    return pointsMessage;
  }



  public void setPointsMessage(String pointsMessage) {
    this.pointsMessage = pointsMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckReturn checkReturn = (CheckReturn) o;
    return Objects.equals(this.points, checkReturn.points) &&
        Objects.equals(this.pointsMessage, checkReturn.pointsMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(points, pointsMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckReturn {\n");
    sb.append("    points: ").append(toIndentedString(points)).append("\n");
    sb.append("    pointsMessage: ").append(toIndentedString(pointsMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

