/*
 * Climate Hero
 * A web app to incentivize users to be more eco-friendly
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineObject2
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-12T18:02:17.553-07:00[America/Los_Angeles]")
public class InlineObject2 {
  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_LIST_ITEMS = "listItems";
  @SerializedName(SERIALIZED_NAME_LIST_ITEMS)
  private List<String> listItems = null;


  public InlineObject2 email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEmail() {
    return email;
  }



  public void setEmail(String email) {
    this.email = email;
  }


  public InlineObject2 listItems(List<String> listItems) {
    
    this.listItems = listItems;
    return this;
  }

  public InlineObject2 addListItemsItem(String listItemsItem) {
    if (this.listItems == null) {
      this.listItems = new ArrayList<String>();
    }
    this.listItems.add(listItemsItem);
    return this;
  }

   /**
   * Get listItems
   * @return listItems
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getListItems() {
    return listItems;
  }



  public void setListItems(List<String> listItems) {
    this.listItems = listItems;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject2 inlineObject2 = (InlineObject2) o;
    return Objects.equals(this.email, inlineObject2.email) &&
        Objects.equals(this.listItems, inlineObject2.listItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, listItems);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject2 {\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    listItems: ").append(toIndentedString(listItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

