/*
 * Climate Hero
 * A web app to incentivize users to be more eco-friendly
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * UserInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-12T18:02:17.553-07:00[America/Los_Angeles]")
public class UserInfo {
  public static final String SERIALIZED_NAME_POINTS = "points";
  @SerializedName(SERIALIZED_NAME_POINTS)
  private Long points;

  public static final String SERIALIZED_NAME_CHECK_LIST = "checkList";
  @SerializedName(SERIALIZED_NAME_CHECK_LIST)
  private List<String> checkList = new ArrayList<String>();

  public static final String SERIALIZED_NAME_POINTS_MESSAGE = "pointsMessage";
  @SerializedName(SERIALIZED_NAME_POINTS_MESSAGE)
  private String pointsMessage;


  public UserInfo points(Long points) {
    
    this.points = points;
    return this;
  }

   /**
   * Get points
   * @return points
  **/
  @ApiModelProperty(required = true, value = "")

  public Long getPoints() {
    return points;
  }



  public void setPoints(Long points) {
    this.points = points;
  }


  public UserInfo checkList(List<String> checkList) {
    
    this.checkList = checkList;
    return this;
  }

  public UserInfo addCheckListItem(String checkListItem) {
    this.checkList.add(checkListItem);
    return this;
  }

   /**
   * Get checkList
   * @return checkList
  **/
  @ApiModelProperty(required = true, value = "")

  public List<String> getCheckList() {
    return checkList;
  }



  public void setCheckList(List<String> checkList) {
    this.checkList = checkList;
  }


  public UserInfo pointsMessage(String pointsMessage) {
    
    this.pointsMessage = pointsMessage;
    return this;
  }

   /**
   * Get pointsMessage
   * @return pointsMessage
  **/
  @ApiModelProperty(required = true, value = "")

  public String getPointsMessage() {
    return pointsMessage;
  }



  public void setPointsMessage(String pointsMessage) {
    this.pointsMessage = pointsMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserInfo userInfo = (UserInfo) o;
    return Objects.equals(this.points, userInfo.points) &&
        Objects.equals(this.checkList, userInfo.checkList) &&
        Objects.equals(this.pointsMessage, userInfo.pointsMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(points, checkList, pointsMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserInfo {\n");
    sb.append("    points: ").append(toIndentedString(points)).append("\n");
    sb.append("    checkList: ").append(toIndentedString(checkList)).append("\n");
    sb.append("    pointsMessage: ").append(toIndentedString(pointsMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

