// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CheckReturn check return
// swagger:model CheckReturn
type CheckReturn struct {

	// points
	// Required: true
	Points *int64 `json:"points"`

	// points message
	// Required: true
	PointsMessage *string `json:"pointsMessage"`
}

// Validate validates this check return
func (m *CheckReturn) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePoints(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePointsMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CheckReturn) validatePoints(formats strfmt.Registry) error {

	if err := validate.Required("points", "body", m.Points); err != nil {
		return err
	}

	return nil
}

func (m *CheckReturn) validatePointsMessage(formats strfmt.Registry) error {

	if err := validate.Required("pointsMessage", "body", m.PointsMessage); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CheckReturn) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CheckReturn) UnmarshalBinary(b []byte) error {
	var res CheckReturn
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
